/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignMembershipRequest } from '../../models/assign-membership-request';
import { MembershipResponse } from '../../models/membership-response';

export interface AssignMembership$Params {
  memberId: number;
      body: AssignMembershipRequest
}

export function assignMembership(http: HttpClient, rootUrl: string, params: AssignMembership$Params, context?: HttpContext): Observable<StrictHttpResponse<MembershipResponse>> {
  const rb = new RequestBuilder(rootUrl, assignMembership.PATH, 'post');
  if (params) {
    rb.path('memberId', params.memberId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MembershipResponse>;
    })
  );
}

assignMembership.PATH = '/api/members/{memberId}/memberships';
