/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MembershipResponse } from '../../models/membership-response';

export interface UnfreezeMembership$Params {
  id: number;
}

export function unfreezeMembership(http: HttpClient, rootUrl: string, params: UnfreezeMembership$Params, context?: HttpContext): Observable<StrictHttpResponse<MembershipResponse>> {
  const rb = new RequestBuilder(rootUrl, unfreezeMembership.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MembershipResponse>;
    })
  );
}

unfreezeMembership.PATH = '/api/memberships/{id}/unfreeze';
