/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AssignMembershipRequest {
  idempotencyKey: string;
  paymentMethod: 'CASH' | 'YAPE' | 'PLIN' | 'CARD';
  paymentReference?: string;
  planId: number;
  price?: number;
}
