/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MeResponse } from '../models/me-response';
export interface AuthResponse {
  accessToken: string;
  expiresIn: number;
  refreshToken: string;
  user: MeResponse;
}
