/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashSessionResponse } from '../models/cash-session-response';
import { PaymentResponse } from '../models/payment-response';
export interface CashSessionDetailResponse {
  payments: Array<PaymentResponse>;
  session: CashSessionResponse;
}
