/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CashTotalsResponse {
  card: number;
  cash: number;
  count: number;
  plin: number;
  total: number;
  yape: number;
}
