/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashTotalsResponse } from '../models/cash-totals-response';
export interface CashSessionResponse {
  closedAt?: (string | null);
  closedByName?: (string | null);
  countedCash?: (number | null);
  difference?: (number | null);
  expectedCash?: (number | null);
  id: number;
  notes?: (string | null);
  openedAt: string;
  openedByName: string;
  openingAmount: number;
  status: 'OPEN' | 'CLOSED';
  totals?: CashTotalsResponse;
}
