/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashSessionDetailResponse } from '../models/cash-session-detail-response';
export interface CashStatusResponse {
  current?: CashSessionDetailResponse;
}
