/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CheckInEntryResponse {
  checkedAt: string;
  id: number;
  memberId?: (number | null);
  memberName?: (string | null);
  method: 'QR' | 'DNI';
  reason?: ('INVALID_CODE' | 'UNKNOWN' | 'MEMBER_INACTIVE' | 'NO_MEMBERSHIP' | 'NOT_STARTED' | 'FROZEN' | 'EXPIRED' | null);
  result: 'ALLOWED' | 'DENIED';
}
