/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CheckInMembershipResponse {
  daysLeft: number;
  endDate: string;
  planName: string;
  status: 'SCHEDULED' | 'ACTIVE' | 'FROZEN' | 'EXPIRED' | 'CANCELLED';
}
