/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CheckInMemberResponse } from '../models/check-in-member-response';
import { CheckInMembershipResponse } from '../models/check-in-membership-response';
export interface CheckInResponse {
  checkedAt: string;
  duplicate: boolean;
  member?: CheckInMemberResponse;
  membership?: CheckInMembershipResponse;
  message: string;
  reason?: ('INVALID_CODE' | 'UNKNOWN' | 'MEMBER_INACTIVE' | 'NO_MEMBERSHIP' | 'NOT_STARTED' | 'FROZEN' | 'EXPIRED' | null);
  result: 'ALLOWED' | 'DENIED';
}
