/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateStaffRequest {
  email: string;
  fullName: string;
  password: string;
  role: 'OWNER' | 'ADMIN' | 'RECEPTIONIST';
}
