/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ExpiringMembershipResponse } from '../models/expiring-membership-response';
export interface DashboardSummaryResponse {
  activeMembers: number;
  checkInsToday: number;
  expiringSoon: Array<ExpiringMembershipResponse>;
  frozenMembers: number;
}
