/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExpiringMembershipResponse {
  daysLeft: number;
  endDate: string;
  memberId: number;
  memberName: string;
  planName: string;
}
