/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashTotalsResponse } from '../models/cash-totals-response';
import { DailyIncomeResponse } from '../models/daily-income-response';
export interface IncomeReportResponse {
  days: Array<DailyIncomeResponse>;
  from: string;
  to: string;
  totals: CashTotalsResponse;
}
