/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeResponse {
  email: string;
  fullName: string;
  gymId: number;
  gymName: string;
  id: number;
  role: 'OWNER' | 'ADMIN' | 'RECEPTIONIST';
}
