/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipResponse } from '../models/membership-response';
export interface MemberDetailResponse {
  active: boolean;
  birthDate?: (string | null);
  createdAt: string;
  currentMembership?: MembershipResponse;
  dni: string;
  email?: (string | null);
  fullName: string;
  id: number;
  memberships: Array<MembershipResponse>;
  notes?: (string | null);
  phone?: (string | null);
}
