/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MembershipResponse {
  daysLeft: number;
  endDate: string;
  frozenDays: number;
  frozenSince?: (string | null);
  id: number;
  planName: string;
  price: number;
  startDate: string;
  status: 'SCHEDULED' | 'ACTIVE' | 'FROZEN' | 'EXPIRED' | 'CANCELLED';
}
