/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberRequest {
  birthDate?: string;
  dni: string;
  email?: string;
  fullName: string;
  notes?: string;
  phone?: string;
}
