/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MembershipPaymentResponse {
  amount: number;
  id: number;
  method: 'CASH' | 'YAPE' | 'PLIN' | 'CARD';
  paidAt: string;
  voided: boolean;
}
