/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MembershipResponse } from '../models/membership-response';
export interface MemberSummaryResponse {
  active: boolean;
  currentMembership?: MembershipResponse;
  dni: string;
  fullName: string;
  id: number;
  phone?: (string | null);
}
