/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MemberSummaryResponse } from '../models/member-summary-response';
export interface PageResponseMemberSummaryResponse {
  items: Array<MemberSummaryResponse>;
  page: number;
  size: number;
  totalItems: number;
  totalPages: number;
}
