/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CheckInEntryResponse } from '../models/check-in-entry-response';
export interface PageResponseCheckInEntryResponse {
  items: Array<CheckInEntryResponse>;
  page: number;
  size: number;
  totalItems: number;
  totalPages: number;
}
