/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CashSessionResponse } from '../models/cash-session-response';
export interface PageResponseCashSessionResponse {
  items: Array<CashSessionResponse>;
  page: number;
  size: number;
  totalItems: number;
  totalPages: number;
}
