/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentResponse {
  amount: number;
  id: number;
  memberId: number;
  memberName: string;
  method: 'CASH' | 'YAPE' | 'PLIN' | 'CARD';
  paidAt: string;
  planName: string;
  receivedByName: string;
  reference?: (string | null);
  voidReason?: (string | null);
  voided: boolean;
}
