/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicMemberCardResponse {
  endDate?: (string | null);
  gymName: string;
  memberName: string;
  payload: string;
  planName?: (string | null);
  status?: ('SCHEDULED' | 'ACTIVE' | 'FROZEN' | 'EXPIRED' | 'CANCELLED' | null);
}
