/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StaffResponse {
  active: boolean;
  createdAt: string;
  email: string;
  fullName: string;
  id: number;
  role: 'OWNER' | 'ADMIN' | 'RECEPTIONIST';
}
