/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberDetailResponse } from '../../models/member-detail-response';

export interface GetMember$Params {
  id: number;
}

export function getMember(http: HttpClient, rootUrl: string, params: GetMember$Params, context?: HttpContext): Observable<StrictHttpResponse<MemberDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, getMember.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MemberDetailResponse>;
    })
  );
}

getMember.PATH = '/api/members/{id}';
