/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseMemberSummaryResponse } from '../../models/page-response-member-summary-response';

export interface SearchMembers$Params {
  q?: string;
  page?: number;
  size?: number;
}

export function searchMembers(http: HttpClient, rootUrl: string, params?: SearchMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseMemberSummaryResponse>> {
  const rb = new RequestBuilder(rootUrl, searchMembers.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseMemberSummaryResponse>;
    })
  );
}

searchMembers.PATH = '/api/members';
