/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberDetailResponse } from '../../models/member-detail-response';
import { SetActiveRequest } from '../../models/set-active-request';

export interface SetMemberActive$Params {
  id: number;
      body: SetActiveRequest
}

export function setMemberActive(http: HttpClient, rootUrl: string, params: SetMemberActive$Params, context?: HttpContext): Observable<StrictHttpResponse<MemberDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, setMemberActive.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MemberDetailResponse>;
    })
  );
}

setMemberActive.PATH = '/api/members/{id}/active';
