/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ListStaff$Params as ListStaff$Params } from './fn/staff/list-staff';
export { listStaff as listStaff } from './fn/staff/list-staff';
export type { CreateStaff$Params as CreateStaff$Params } from './fn/staff/create-staff';
export { createStaff as createStaff } from './fn/staff/create-staff';
export type { UpdateStaff$Params as UpdateStaff$Params } from './fn/staff/update-staff';
export { updateStaff as updateStaff } from './fn/staff/update-staff';
export type { RegisterGym$Params as RegisterGym$Params } from './fn/auth/register-gym';
export { registerGym as registerGym } from './fn/auth/register-gym';
export type { Refresh$Params as Refresh$Params } from './fn/auth/refresh';
export { refresh as refresh } from './fn/auth/refresh';
export type { Logout$Params as Logout$Params } from './fn/auth/logout';
export { logout as logout } from './fn/auth/logout';
export type { Login$Params as Login$Params } from './fn/auth/login';
export { login as login } from './fn/auth/login';
export type { GetMe$Params as GetMe$Params } from './fn/me/get-me';
export { getMe as getMe } from './fn/me/get-me';
