/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashSessionDetailResponse } from '../../models/cash-session-detail-response';
import { CloseCashRequest } from '../../models/close-cash-request';

export interface CloseCash$Params {
      body: CloseCashRequest
}

export function closeCash(http: HttpClient, rootUrl: string, params: CloseCash$Params, context?: HttpContext): Observable<StrictHttpResponse<CashSessionDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, closeCash.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashSessionDetailResponse>;
    })
  );
}

closeCash.PATH = '/api/cash/close';
