/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashSessionDetailResponse } from '../../models/cash-session-detail-response';

export interface GetCashSession$Params {
  id: number;
}

export function getCashSession(http: HttpClient, rootUrl: string, params: GetCashSession$Params, context?: HttpContext): Observable<StrictHttpResponse<CashSessionDetailResponse>> {
  const rb = new RequestBuilder(rootUrl, getCashSession.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashSessionDetailResponse>;
    })
  );
}

getCashSession.PATH = '/api/cash/sessions/{id}';
