/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CashStatusResponse } from '../../models/cash-status-response';

export interface GetCurrentCash$Params {
}

export function getCurrentCash(http: HttpClient, rootUrl: string, params?: GetCurrentCash$Params, context?: HttpContext): Observable<StrictHttpResponse<CashStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getCurrentCash.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CashStatusResponse>;
    })
  );
}

getCurrentCash.PATH = '/api/cash/current';
