/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCashSessionResponse } from '../../models/page-response-cash-session-response';

export interface ListCashSessions$Params {
  page?: number;
  size?: number;
}

export function listCashSessions(http: HttpClient, rootUrl: string, params?: ListCashSessions$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCashSessionResponse>> {
  const rb = new RequestBuilder(rootUrl, listCashSessions.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCashSessionResponse>;
    })
  );
}

listCashSessions.PATH = '/api/cash/sessions';
