/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StaffResponse } from '../../models/staff-response';
import { UpdateStaffRequest } from '../../models/update-staff-request';

export interface UpdateStaff$Params {
  id: number;
      body: UpdateStaffRequest
}

export function updateStaff(http: HttpClient, rootUrl: string, params: UpdateStaff$Params, context?: HttpContext): Observable<StrictHttpResponse<StaffResponse>> {
  const rb = new RequestBuilder(rootUrl, updateStaff.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StaffResponse>;
    })
  );
}

updateStaff.PATH = '/api/staff/{id}';
