CREATE TABLE IF NOT EXISTS public.gyms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

-- Login lookup: an email belongs to exactly one gym, so login only needs email + password.
CREATE TABLE IF NOT EXISTS public.accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gym_id BIGINT NOT NULL REFERENCES public.gyms(id),
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uq_accounts_email UNIQUE (email)
);

-- Resolves the gym (tenant) of a public member card link without authentication.
CREATE TABLE IF NOT EXISTS public.member_card_tokens (
    token UUID PRIMARY KEY,
    gym_id BIGINT NOT NULL REFERENCES public.gyms(id)
);
