/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseCheckInEntryResponse } from '../../models/page-response-check-in-entry-response';

export interface ListCheckIns$Params {
  date?: string;
  page?: number;
  size?: number;
}

export function listCheckIns(http: HttpClient, rootUrl: string, params?: ListCheckIns$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCheckInEntryResponse>> {
  const rb = new RequestBuilder(rootUrl, listCheckIns.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseCheckInEntryResponse>;
    })
  );
}

listCheckIns.PATH = '/api/check-ins';
