/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlanResponse } from '../../models/plan-response';

export interface ListPlans$Params {
  includeInactive?: boolean;
}

export function listPlans(http: HttpClient, rootUrl: string, params?: ListPlans$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PlanResponse>>> {
  const rb = new RequestBuilder(rootUrl, listPlans.PATH, 'get');
  if (params) {
    rb.query('includeInactive', params.includeInactive, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PlanResponse>>;
    })
  );
}

listPlans.PATH = '/api/plans';
