/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PlanRequest } from '../../models/plan-request';
import { PlanResponse } from '../../models/plan-response';

export interface UpdatePlan$Params {
  id: number;
      body: PlanRequest
}

export function updatePlan(http: HttpClient, rootUrl: string, params: UpdatePlan$Params, context?: HttpContext): Observable<StrictHttpResponse<PlanResponse>> {
  const rb = new RequestBuilder(rootUrl, updatePlan.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PlanResponse>;
    })
  );
}

updatePlan.PATH = '/api/plans/{id}';
